<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Notepal.Shared\Notepal.Shared.csproj" />
    <ProjectReference Include="..\Notepal.ServiceDefaults\Notepal.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Web" />
    <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>e620f6ed-0497-474e-868c-431e75f1b930</UserSecretsId>
  </PropertyGroup>

</Project>
